config/routes.rb
Rails.application.routes.draw do
  root "pages#show", page: "home"

  resources :locations, param: :slug, only: [:index, :show]
  resources :images, param: :slug, only: [:show]

  get ":page" => "pages#show"





end


# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<h1 class="title">Duarte de Armas' <em>Livro das Fortalezas</em></h1>
<br/>
<p>
  The aim of this project is to spatially reconstruct an exceptional architectural source from early modern Portugal called the <em>Livro das Fortalezas</em> (Book of Fortresses). This bound volume was created by a Portuguese squire named Duarte de Armas in 1510. It includes a folio of perspective drawings from two vantage-points of over 50 castles on the border between the kingdoms of Portugal and Spain and a second folio of measured plans for each site. With the assistance of student researchers, the book will be reconstructed as a data-rich, three-dimensional map. Sub-projects will include 3D models of the fortresses based on Duarte de Armas’ plans and drawings, a database identifying architectural features and scenes from daily life in the drawings, and GIS layers designed to study how the castles formed a fortified chain on the border with Spain. Future plans include a photogrammetric analysis of the sites in order to determine with greater precision where Duarte de Armas had to be standing when he drew the perspectival drawings, how accurate he was in terms of perspective, scale and detail, and how these castles and towns have changed since 1510.
</p>
<br/>
<p>
This project is in collaboration with <a href="http://www.dukewired.org/projects/the-book-of-fortresses/">Wired!</a> at Duke University.
</p>
<br/>
<br/>
<div class="parallax"></div>
<br/>
<br/>
<h2>Explore Recent Sites:</h2>
<br/>
<div id="home_sites_gallery_wrapper">
  <div id="home_sites_gallery">
    <!-- Castro Marim -->
      <a href="<%= location_path ('castro-marim') %>" class="home_site_card">
      <div class="home_site_card_image" id="home_site_1">
      </div>
      <div class="home_site_card_metadata">
        <br/>
        <h3>Castro Marim</h3>
      </div>
    </a>
    <!-- Alcoutim -->
    <a href="<%= location_path ('alcoutim') %>" class="home_site_card">
    <div class="home_site_card_image" id="home_site_2">
    </div>
    <div class="home_site_card_metadata">
      <br/>
      <h3>Alcoutim</h3>
    </div>
  </a>
    <!-- Serpa -->
    <a href="<%= location_path ('serpa') %>" class="home_site_card">
    <div class="home_site_card_image" id="home_site_3">
    </div>
    <div class="home_site_card_metadata">
      <br/>
      <h3>Serpa</h3>
    </div>
  </a>
  </div>
</div>
<br/>
<br/>
<br/>
<div id="home_row2">
  <h2>View All Locations: <%= link_to 'Locations', locations_path %></h2>
</div>
<br/>
<br/>
<br/>
<br/>