config/routes.rb
Rails.application.routes.draw do
  root "pages#show", page: "home"

  resources :locations, param: :slug, only: [:index, :show]
  resources :images, param: :slug, only: [:show]

  get ":page" => "pages#show"





end


# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :location, :foreign_key => 'at_locations_table_id', :primary_key => 'at_locations_table_id', optional: true

  def title
    title = ""
    if source
      title.concat(formatted_source)
    end
    if view_direction
       title.concat(", view: #{view_direction}")
    end
    if image_category == "satellite image"
      title.concat(" Satellite Image")
    end
    if image_category == "plan"
      title.concat(" Plan")
    end
    title.strip
  end

  def formatted_source
    case source
    when "1642_watercolor"
      "1642 Watercolor"
    else
      source
    end
  end

  def agol_iframe
    return agol_slide_embed if agol_slide_embed.include? 'iframe'
    '<iframe width="800" height="600" frameborder="0" scrolling="no" allowfullscreen src=' + '"' + agol_slide_embed + '"' + '></iframe>'
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_action :set_image, only: [:show, :edit, :update, :destroy]

  def index
    @images = Image.all
  end

  def show
    render :show
  end

  def create
    @image = Image.new(image_params)
  end

  private
    def set_image
      @image = Image.find_by(slug: params[:slug])
    end

    def image_params
      params.permit(:at_image_id, :slug, :at_images_table_id, :at_locations_table_id, :url, :filename, :size, :image_type, :image_category, :source, :page_number, :primary_site_name, :view_direction, :secondary_site_name, :secondary_site_kingdom, :number_of_watchtowers, :exterior_features, :status, :fortress_features, :agol_slide_embed, :at_images_table_time_created, :small_thumbnail_url, :small_thumbnail_width, :small_thumbnail_height, :large_thumbnail_url, :large_thumbnail_width, :large_thumbnail_height)
    end
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/views/images/_form.html.erb
<%= form_with(model: image, local: true) do |form| %>
  <% if image.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(image.errors.count, "error") %> prohibited this image from being saved:</h2>

      <ul>
      <% image.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/images/edit.html.erb
<h1>Editing Image</h1>

<%= render 'form', image: @image %>

<%= link_to 'Show', @image %> |
<%= link_to 'Back', images_path %>

app/views/images/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Images</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @images.each do |image| %>
      <tr>
        <td><%= link_to 'Show', image %></td>
        <td><%= link_to 'Edit', edit_image_path(image) %></td>
        <td><%= link_to 'Destroy', image, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Image', new_image_path %>

app/views/images/new.html.erb
<h1>New Image</h1>

<%= render 'form', image: @image %>

<%= link_to 'Back', images_path %>

app/views/images/show.html.erb
<div id="image_wrapper">
  <div id="image_column_one">
    <h1><%= @image.location.primary_site_name %></h1>
    <h2>Source: <%= @image.source %></h2>
    <h2>View: <%= @image.view_direction %></h2>
    <% if @image.fortress_features %>
      <h2>Suggested fortress tags: <%= @image.fortress_features %></h2>
    <% end %>
    <% if @image.exterior_features %>
      <h2>Suggested exterior tags: <%= @image.exterior_features %></h2>
    <% end %>
  </div>

    <div id="annotatable_image_wrapper">
      <img src='<%= @image.url %>' class="annotatable"></img>
    </div>

</div>

<script>
// Logs newly-created annotations to the console
anno.addHandler('onAnnotationCreated', function(annotation) {
  console.log(annotation.text);
});
</script>

<!-- <button onclick="anno.activateSelector();" href="#">
  ADD ANNOTATION
</button>

<div id="annotorious_wrapper">
  <div id="annotorious" class="openseadragon"></div>
</div>

<script type="text/javascript">


var viewer = OpenSeadragon({
  id: "annotorious",
  showNavigator: false,
  tileSources: {
    type: 'image',
    url: '<%= @image.url %>'
  }
});

anno.makeAnnotatable(viewer);

</script> -->